/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardSummary {
  'endpoint_status' : string,
  'no_trade_count' : bigint,
  'system_mode' : string,
  'total_articles_consumed' : bigint,
  'pending_candidates' : bigint,
  'last_refresh' : bigint,
  'articles_processed_today' : bigint,
  'active_opportunities' : bigint,
}
export interface NewsArticleRef {
  'id' : string,
  'title' : string,
  'news_category' : string,
  'source' : string,
  'executive_summary' : string,
  'image_url' : [] | [string],
  'affected_symbols' : Array<string>,
  'impact_score' : number,
  'raw_analysis_data' : string,
  'analyzed_at' : bigint,
  'description' : string,
  'published_at' : bigint,
  'news_relevance' : string,
  'processing_status' : string,
  'impact_summary' : string,
}
export interface ProcessingState {
  'is_polling_active' : boolean,
  'last_processed_article_id' : [] | [string],
  'articles_in_queue' : bigint,
  'current_mode' : string,
  'total_articles_processed' : bigint,
  'last_poll_timestamp' : bigint,
}
export interface SystemConfig {
  'processing_mode' : string,
  'news_endpoint_url' : string,
  'use_mock_data' : boolean,
  'risk_per_trade_pct' : number,
  'min_rr' : number,
  'max_open_positions' : bigint,
  'capital' : number,
  'max_daily_loss_pct' : number,
  'polling_interval_mins' : bigint,
}
export interface _SERVICE {
  'fetch_news' : ActorMethod<[], string>,
  'filter_news' : ActorMethod<
    [[] | [string], [] | [string], [] | [number]],
    Array<NewsArticleRef>
  >,
  'get_config' : ActorMethod<[], SystemConfig>,
  'get_dashboard_summary' : ActorMethod<[], DashboardSummary>,
  'get_news' : ActorMethod<[bigint, bigint], Array<NewsArticleRef>>,
  'get_news_by_id' : ActorMethod<[string], [] | [NewsArticleRef]>,
  'get_processing_state' : ActorMethod<[], ProcessingState>,
  'get_total_news_count' : ActorMethod<[], bigint>,
  'reset_config' : ActorMethod<[], SystemConfig>,
  'update_config' : ActorMethod<[SystemConfig], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];