/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NewsArticleRef = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'news_category' : IDL.Text,
  'source' : IDL.Text,
  'executive_summary' : IDL.Text,
  'image_url' : IDL.Opt(IDL.Text),
  'affected_symbols' : IDL.Vec(IDL.Text),
  'impact_score' : IDL.Float64,
  'raw_analysis_data' : IDL.Text,
  'analyzed_at' : IDL.Int,
  'description' : IDL.Text,
  'published_at' : IDL.Int,
  'news_relevance' : IDL.Text,
  'processing_status' : IDL.Text,
  'impact_summary' : IDL.Text,
});
export const SystemConfig = IDL.Record({
  'processing_mode' : IDL.Text,
  'news_endpoint_url' : IDL.Text,
  'use_mock_data' : IDL.Bool,
  'risk_per_trade_pct' : IDL.Float64,
  'min_rr' : IDL.Float64,
  'max_open_positions' : IDL.Nat,
  'capital' : IDL.Float64,
  'max_daily_loss_pct' : IDL.Float64,
  'polling_interval_mins' : IDL.Nat,
});
export const DashboardSummary = IDL.Record({
  'endpoint_status' : IDL.Text,
  'no_trade_count' : IDL.Nat,
  'system_mode' : IDL.Text,
  'total_articles_consumed' : IDL.Nat,
  'pending_candidates' : IDL.Nat,
  'last_refresh' : IDL.Int,
  'articles_processed_today' : IDL.Nat,
  'active_opportunities' : IDL.Nat,
});
export const ProcessingState = IDL.Record({
  'is_polling_active' : IDL.Bool,
  'last_processed_article_id' : IDL.Opt(IDL.Text),
  'articles_in_queue' : IDL.Nat,
  'current_mode' : IDL.Text,
  'total_articles_processed' : IDL.Nat,
  'last_poll_timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'fetch_news' : IDL.Func([], [IDL.Text], []),
  'filter_news' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Float64)],
      [IDL.Vec(NewsArticleRef)],
      [],
    ),
  'get_config' : IDL.Func([], [SystemConfig], []),
  'get_dashboard_summary' : IDL.Func([], [DashboardSummary], []),
  'get_news' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(NewsArticleRef)], []),
  'get_news_by_id' : IDL.Func([IDL.Text], [IDL.Opt(NewsArticleRef)], []),
  'get_processing_state' : IDL.Func([], [ProcessingState], []),
  'get_total_news_count' : IDL.Func([], [IDL.Nat], []),
  'reset_config' : IDL.Func([], [SystemConfig], []),
  'update_config' : IDL.Func([SystemConfig], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NewsArticleRef = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'news_category' : IDL.Text,
    'source' : IDL.Text,
    'executive_summary' : IDL.Text,
    'image_url' : IDL.Opt(IDL.Text),
    'affected_symbols' : IDL.Vec(IDL.Text),
    'impact_score' : IDL.Float64,
    'raw_analysis_data' : IDL.Text,
    'analyzed_at' : IDL.Int,
    'description' : IDL.Text,
    'published_at' : IDL.Int,
    'news_relevance' : IDL.Text,
    'processing_status' : IDL.Text,
    'impact_summary' : IDL.Text,
  });
  const SystemConfig = IDL.Record({
    'processing_mode' : IDL.Text,
    'news_endpoint_url' : IDL.Text,
    'use_mock_data' : IDL.Bool,
    'risk_per_trade_pct' : IDL.Float64,
    'min_rr' : IDL.Float64,
    'max_open_positions' : IDL.Nat,
    'capital' : IDL.Float64,
    'max_daily_loss_pct' : IDL.Float64,
    'polling_interval_mins' : IDL.Nat,
  });
  const DashboardSummary = IDL.Record({
    'endpoint_status' : IDL.Text,
    'no_trade_count' : IDL.Nat,
    'system_mode' : IDL.Text,
    'total_articles_consumed' : IDL.Nat,
    'pending_candidates' : IDL.Nat,
    'last_refresh' : IDL.Int,
    'articles_processed_today' : IDL.Nat,
    'active_opportunities' : IDL.Nat,
  });
  const ProcessingState = IDL.Record({
    'is_polling_active' : IDL.Bool,
    'last_processed_article_id' : IDL.Opt(IDL.Text),
    'articles_in_queue' : IDL.Nat,
    'current_mode' : IDL.Text,
    'total_articles_processed' : IDL.Nat,
    'last_poll_timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'fetch_news' : IDL.Func([], [IDL.Text], []),
    'filter_news' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Float64)],
        [IDL.Vec(NewsArticleRef)],
        [],
      ),
    'get_config' : IDL.Func([], [SystemConfig], []),
    'get_dashboard_summary' : IDL.Func([], [DashboardSummary], []),
    'get_news' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(NewsArticleRef)], []),
    'get_news_by_id' : IDL.Func([IDL.Text], [IDL.Opt(NewsArticleRef)], []),
    'get_processing_state' : IDL.Func([], [ProcessingState], []),
    'get_total_news_count' : IDL.Func([], [IDL.Nat], []),
    'reset_config' : IDL.Func([], [SystemConfig], []),
    'update_config' : IDL.Func([SystemConfig], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };