/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradePlannerRouteImport } from './routes/trade-planner'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as NewsFeedRouteImport } from './routes/news-feed'
import { Route as ModeAnalysisRouteImport } from './routes/mode-analysis'
import { Route as MarketRegimeRouteImport } from './routes/market-regime'
import { Route as MarketOpenRouteImport } from './routes/market-open'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GroupingRouteImport } from './routes/grouping'
import { Route as ExecutionPlannerRouteImport } from './routes/execution-planner'
import { Route as AgentSignalsRouteImport } from './routes/agent-signals'
import { Route as Agent1ResultsRouteImport } from './routes/agent-1-results'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SymbolsSymbolIdRouteImport } from './routes/symbols.$symbolId'

const TradePlannerRoute = TradePlannerRouteImport.update({
  id: '/trade-planner',
  path: '/trade-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsFeedRoute = NewsFeedRouteImport.update({
  id: '/news-feed',
  path: '/news-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeAnalysisRoute = ModeAnalysisRouteImport.update({
  id: '/mode-analysis',
  path: '/mode-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRegimeRoute = MarketRegimeRouteImport.update({
  id: '/market-regime',
  path: '/market-regime',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketOpenRoute = MarketOpenRouteImport.update({
  id: '/market-open',
  path: '/market-open',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupingRoute = GroupingRouteImport.update({
  id: '/grouping',
  path: '/grouping',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionPlannerRoute = ExecutionPlannerRouteImport.update({
  id: '/execution-planner',
  path: '/execution-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSignalsRoute = AgentSignalsRouteImport.update({
  id: '/agent-signals',
  path: '/agent-signals',
  getParentRoute: () => rootRouteImport,
} as any)
const Agent1ResultsRoute = Agent1ResultsRouteImport.update({
  id: '/agent-1-results',
  path: '/agent-1-results',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SymbolsSymbolIdRoute = SymbolsSymbolIdRouteImport.update({
  id: '/symbols/$symbolId',
  path: '/symbols/$symbolId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-1-results': typeof Agent1ResultsRoute
  '/agent-signals': typeof AgentSignalsRoute
  '/execution-planner': typeof ExecutionPlannerRoute
  '/grouping': typeof GroupingRoute
  '/journal': typeof JournalRoute
  '/market-open': typeof MarketOpenRoute
  '/market-regime': typeof MarketRegimeRoute
  '/mode-analysis': typeof ModeAnalysisRoute
  '/news-feed': typeof NewsFeedRoute
  '/opportunities': typeof OpportunitiesRoute
  '/settings': typeof SettingsRoute
  '/trade-planner': typeof TradePlannerRoute
  '/symbols/$symbolId': typeof SymbolsSymbolIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-1-results': typeof Agent1ResultsRoute
  '/agent-signals': typeof AgentSignalsRoute
  '/execution-planner': typeof ExecutionPlannerRoute
  '/grouping': typeof GroupingRoute
  '/journal': typeof JournalRoute
  '/market-open': typeof MarketOpenRoute
  '/market-regime': typeof MarketRegimeRoute
  '/mode-analysis': typeof ModeAnalysisRoute
  '/news-feed': typeof NewsFeedRoute
  '/opportunities': typeof OpportunitiesRoute
  '/settings': typeof SettingsRoute
  '/trade-planner': typeof TradePlannerRoute
  '/symbols/$symbolId': typeof SymbolsSymbolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-1-results': typeof Agent1ResultsRoute
  '/agent-signals': typeof AgentSignalsRoute
  '/execution-planner': typeof ExecutionPlannerRoute
  '/grouping': typeof GroupingRoute
  '/journal': typeof JournalRoute
  '/market-open': typeof MarketOpenRoute
  '/market-regime': typeof MarketRegimeRoute
  '/mode-analysis': typeof ModeAnalysisRoute
  '/news-feed': typeof NewsFeedRoute
  '/opportunities': typeof OpportunitiesRoute
  '/settings': typeof SettingsRoute
  '/trade-planner': typeof TradePlannerRoute
  '/symbols/$symbolId': typeof SymbolsSymbolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-1-results'
    | '/agent-signals'
    | '/execution-planner'
    | '/grouping'
    | '/journal'
    | '/market-open'
    | '/market-regime'
    | '/mode-analysis'
    | '/news-feed'
    | '/opportunities'
    | '/settings'
    | '/trade-planner'
    | '/symbols/$symbolId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-1-results'
    | '/agent-signals'
    | '/execution-planner'
    | '/grouping'
    | '/journal'
    | '/market-open'
    | '/market-regime'
    | '/mode-analysis'
    | '/news-feed'
    | '/opportunities'
    | '/settings'
    | '/trade-planner'
    | '/symbols/$symbolId'
  id:
    | '__root__'
    | '/'
    | '/agent-1-results'
    | '/agent-signals'
    | '/execution-planner'
    | '/grouping'
    | '/journal'
    | '/market-open'
    | '/market-regime'
    | '/mode-analysis'
    | '/news-feed'
    | '/opportunities'
    | '/settings'
    | '/trade-planner'
    | '/symbols/$symbolId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Agent1ResultsRoute: typeof Agent1ResultsRoute
  AgentSignalsRoute: typeof AgentSignalsRoute
  ExecutionPlannerRoute: typeof ExecutionPlannerRoute
  GroupingRoute: typeof GroupingRoute
  JournalRoute: typeof JournalRoute
  MarketOpenRoute: typeof MarketOpenRoute
  MarketRegimeRoute: typeof MarketRegimeRoute
  ModeAnalysisRoute: typeof ModeAnalysisRoute
  NewsFeedRoute: typeof NewsFeedRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  SettingsRoute: typeof SettingsRoute
  TradePlannerRoute: typeof TradePlannerRoute
  SymbolsSymbolIdRoute: typeof SymbolsSymbolIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade-planner': {
      id: '/trade-planner'
      path: '/trade-planner'
      fullPath: '/trade-planner'
      preLoaderRoute: typeof TradePlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-feed': {
      id: '/news-feed'
      path: '/news-feed'
      fullPath: '/news-feed'
      preLoaderRoute: typeof NewsFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mode-analysis': {
      id: '/mode-analysis'
      path: '/mode-analysis'
      fullPath: '/mode-analysis'
      preLoaderRoute: typeof ModeAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-regime': {
      id: '/market-regime'
      path: '/market-regime'
      fullPath: '/market-regime'
      preLoaderRoute: typeof MarketRegimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-open': {
      id: '/market-open'
      path: '/market-open'
      fullPath: '/market-open'
      preLoaderRoute: typeof MarketOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grouping': {
      id: '/grouping'
      path: '/grouping'
      fullPath: '/grouping'
      preLoaderRoute: typeof GroupingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution-planner': {
      id: '/execution-planner'
      path: '/execution-planner'
      fullPath: '/execution-planner'
      preLoaderRoute: typeof ExecutionPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-signals': {
      id: '/agent-signals'
      path: '/agent-signals'
      fullPath: '/agent-signals'
      preLoaderRoute: typeof AgentSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-1-results': {
      id: '/agent-1-results'
      path: '/agent-1-results'
      fullPath: '/agent-1-results'
      preLoaderRoute: typeof Agent1ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symbols/$symbolId': {
      id: '/symbols/$symbolId'
      path: '/symbols/$symbolId'
      fullPath: '/symbols/$symbolId'
      preLoaderRoute: typeof SymbolsSymbolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Agent1ResultsRoute: Agent1ResultsRoute,
  AgentSignalsRoute: AgentSignalsRoute,
  ExecutionPlannerRoute: ExecutionPlannerRoute,
  GroupingRoute: GroupingRoute,
  JournalRoute: JournalRoute,
  MarketOpenRoute: MarketOpenRoute,
  MarketRegimeRoute: MarketRegimeRoute,
  ModeAnalysisRoute: ModeAnalysisRoute,
  NewsFeedRoute: NewsFeedRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  SettingsRoute: SettingsRoute,
  TradePlannerRoute: TradePlannerRoute,
  SymbolsSymbolIdRoute: SymbolsSymbolIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
