/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SystemConfig {
    processing_mode: string;
    news_endpoint_url: string;
    use_mock_data: boolean;
    risk_per_trade_pct: number;
    min_rr: number;
    max_open_positions: bigint;
    capital: number;
    max_daily_loss_pct: number;
    polling_interval_mins: bigint;
}
export interface NewsArticleRef {
    id: string;
    title: string;
    news_category: string;
    source: string;
    executive_summary: string;
    image_url?: string;
    affected_symbols: Array<string>;
    impact_score: number;
    raw_analysis_data: string;
    analyzed_at: bigint;
    description: string;
    published_at: bigint;
    news_relevance: string;
    processing_status: string;
    impact_summary: string;
}
export interface ProcessingState {
    is_polling_active: boolean;
    last_processed_article_id?: string;
    articles_in_queue: bigint;
    current_mode: string;
    total_articles_processed: bigint;
    last_poll_timestamp: bigint;
}
export interface DashboardSummary {
    endpoint_status: string;
    no_trade_count: bigint;
    system_mode: string;
    total_articles_consumed: bigint;
    pending_candidates: bigint;
    last_refresh: bigint;
    articles_processed_today: bigint;
    active_opportunities: bigint;
}
export interface backendInterface {
    fetch_news(): Promise<string>;
    filter_news(symbol: string | null, category: string | null, min_impact: number | null): Promise<Array<NewsArticleRef>>;
    get_config(): Promise<SystemConfig>;
    get_dashboard_summary(): Promise<DashboardSummary>;
    get_news(page: bigint, page_size: bigint): Promise<Array<NewsArticleRef>>;
    get_news_by_id(id: string): Promise<NewsArticleRef | null>;
    get_processing_state(): Promise<ProcessingState>;
    get_total_news_count(): Promise<bigint>;
    reset_config(): Promise<SystemConfig>;
    update_config(cfg: SystemConfig): Promise<boolean>;
}
import type { NewsArticleRef as _NewsArticleRef, ProcessingState as _ProcessingState } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async fetch_news(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetch_news();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetch_news();
            return result;
        }
    }
    async filter_news(arg0: string | null, arg1: string | null, arg2: number | null): Promise<Array<NewsArticleRef>> {
        if (this.processError) {
            try {
                const result = await this.actor.filter_news(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filter_news(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_config(): Promise<SystemConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.get_config();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_config();
            return result;
        }
    }
    async get_dashboard_summary(): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.get_dashboard_summary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_dashboard_summary();
            return result;
        }
    }
    async get_news(arg0: bigint, arg1: bigint): Promise<Array<NewsArticleRef>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_news(arg0, arg1);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_news(arg0, arg1);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_news_by_id(arg0: string): Promise<NewsArticleRef | null> {
        if (this.processError) {
            try {
                const result = await this.actor.get_news_by_id(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_news_by_id(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_processing_state(): Promise<ProcessingState> {
        if (this.processError) {
            try {
                const result = await this.actor.get_processing_state();
                return from_candid_ProcessingState_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_processing_state();
            return from_candid_ProcessingState_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_total_news_count(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.get_total_news_count();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_total_news_count();
            return result;
        }
    }
    async reset_config(): Promise<SystemConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.reset_config();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reset_config();
            return result;
        }
    }
    async update_config(arg0: SystemConfig): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.update_config(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_config(arg0);
            return result;
        }
    }
}
function from_candid_NewsArticleRef_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsArticleRef): NewsArticleRef {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ProcessingState_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProcessingState): ProcessingState {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NewsArticleRef]): NewsArticleRef | null {
    return value.length === 0 ? null : from_candid_NewsArticleRef_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    news_category: string;
    source: string;
    executive_summary: string;
    image_url: [] | [string];
    affected_symbols: Array<string>;
    impact_score: number;
    raw_analysis_data: string;
    analyzed_at: bigint;
    description: string;
    published_at: bigint;
    news_relevance: string;
    processing_status: string;
    impact_summary: string;
}): {
    id: string;
    title: string;
    news_category: string;
    source: string;
    executive_summary: string;
    image_url?: string;
    affected_symbols: Array<string>;
    impact_score: number;
    raw_analysis_data: string;
    analyzed_at: bigint;
    description: string;
    published_at: bigint;
    news_relevance: string;
    processing_status: string;
    impact_summary: string;
} {
    return {
        id: value.id,
        title: value.title,
        news_category: value.news_category,
        source: value.source,
        executive_summary: value.executive_summary,
        image_url: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.image_url)),
        affected_symbols: value.affected_symbols,
        impact_score: value.impact_score,
        raw_analysis_data: value.raw_analysis_data,
        analyzed_at: value.analyzed_at,
        description: value.description,
        published_at: value.published_at,
        news_relevance: value.news_relevance,
        processing_status: value.processing_status,
        impact_summary: value.impact_summary
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    is_polling_active: boolean;
    last_processed_article_id: [] | [string];
    articles_in_queue: bigint;
    current_mode: string;
    total_articles_processed: bigint;
    last_poll_timestamp: bigint;
}): {
    is_polling_active: boolean;
    last_processed_article_id?: string;
    articles_in_queue: bigint;
    current_mode: string;
    total_articles_processed: bigint;
    last_poll_timestamp: bigint;
} {
    return {
        is_polling_active: value.is_polling_active,
        last_processed_article_id: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.last_processed_article_id)),
        articles_in_queue: value.articles_in_queue,
        current_mode: value.current_mode,
        total_articles_processed: value.total_articles_processed,
        last_poll_timestamp: value.last_poll_timestamp
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewsArticleRef>): Array<NewsArticleRef> {
    return value.map((x)=>from_candid_NewsArticleRef_n4(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
