/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as JournalImport } from "./routes/journal";
import { Route as MarketRegimeImport } from "./routes/market-regime";
import { Route as ModeAnalysisImport } from "./routes/mode-analysis";
import { Route as NewsFeedImport } from "./routes/news-feed";
import { Route as OpportunitiesImport } from "./routes/opportunities";
import { Route as SettingsImport } from "./routes/settings";
import { Route as SymbolsSymbolIdImport } from "./routes/symbols.$symbolId";
import { Route as TradePlannerImport } from "./routes/trade-planner";

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRoute,
} as any);

const OpportunitiesRoute = OpportunitiesImport.update({
  id: "/opportunities",
  path: "/opportunities",
  getParentRoute: () => rootRoute,
} as any);

const NewsFeedRoute = NewsFeedImport.update({
  id: "/news-feed",
  path: "/news-feed",
  getParentRoute: () => rootRoute,
} as any);

const ModeAnalysisRoute = ModeAnalysisImport.update({
  id: "/mode-analysis",
  path: "/mode-analysis",
  getParentRoute: () => rootRoute,
} as any);

const MarketRegimeRoute = MarketRegimeImport.update({
  id: "/market-regime",
  path: "/market-regime",
  getParentRoute: () => rootRoute,
} as any);

const JournalRoute = JournalImport.update({
  id: "/journal",
  path: "/journal",
  getParentRoute: () => rootRoute,
} as any);

const TradePlannerRoute = TradePlannerImport.update({
  id: "/trade-planner",
  path: "/trade-planner",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const SymbolsSymbolIdRoute = SymbolsSymbolIdImport.update({
  id: "/symbols/$symbolId",
  path: "/symbols/$symbolId",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsImport;
      parentRoute: typeof rootRoute;
    };
    "/opportunities": {
      id: "/opportunities";
      path: "/opportunities";
      fullPath: "/opportunities";
      preLoaderRoute: typeof OpportunitiesImport;
      parentRoute: typeof rootRoute;
    };
    "/news-feed": {
      id: "/news-feed";
      path: "/news-feed";
      fullPath: "/news-feed";
      preLoaderRoute: typeof NewsFeedImport;
      parentRoute: typeof rootRoute;
    };
    "/mode-analysis": {
      id: "/mode-analysis";
      path: "/mode-analysis";
      fullPath: "/mode-analysis";
      preLoaderRoute: typeof ModeAnalysisImport;
      parentRoute: typeof rootRoute;
    };
    "/market-regime": {
      id: "/market-regime";
      path: "/market-regime";
      fullPath: "/market-regime";
      preLoaderRoute: typeof MarketRegimeImport;
      parentRoute: typeof rootRoute;
    };
    "/journal": {
      id: "/journal";
      path: "/journal";
      fullPath: "/journal";
      preLoaderRoute: typeof JournalImport;
      parentRoute: typeof rootRoute;
    };
    "/trade-planner": {
      id: "/trade-planner";
      path: "/trade-planner";
      fullPath: "/trade-planner";
      preLoaderRoute: typeof TradePlannerImport;
      parentRoute: typeof rootRoute;
    };
    "/symbols/$symbolId": {
      id: "/symbols/$symbolId";
      path: "/symbols/$symbolId";
      fullPath: "/symbols/$symbolId";
      preLoaderRoute: typeof SymbolsSymbolIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/opportunities": typeof OpportunitiesRoute;
  "/news-feed": typeof NewsFeedRoute;
  "/mode-analysis": typeof ModeAnalysisRoute;
  "/market-regime": typeof MarketRegimeRoute;
  "/journal": typeof JournalRoute;
  "/trade-planner": typeof TradePlannerRoute;
  "/symbols/$symbolId": typeof SymbolsSymbolIdRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/opportunities": typeof OpportunitiesRoute;
  "/news-feed": typeof NewsFeedRoute;
  "/mode-analysis": typeof ModeAnalysisRoute;
  "/market-regime": typeof MarketRegimeRoute;
  "/journal": typeof JournalRoute;
  "/trade-planner": typeof TradePlannerRoute;
  "/symbols/$symbolId": typeof SymbolsSymbolIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/opportunities": typeof OpportunitiesRoute;
  "/news-feed": typeof NewsFeedRoute;
  "/mode-analysis": typeof ModeAnalysisRoute;
  "/market-regime": typeof MarketRegimeRoute;
  "/journal": typeof JournalRoute;
  "/trade-planner": typeof TradePlannerRoute;
  "/symbols/$symbolId": typeof SymbolsSymbolIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fileRoutesByTo: FileRoutesByTo;
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SettingsRoute: typeof SettingsRoute;
  OpportunitiesRoute: typeof OpportunitiesRoute;
  NewsFeedRoute: typeof NewsFeedRoute;
  ModeAnalysisRoute: typeof ModeAnalysisRoute;
  MarketRegimeRoute: typeof MarketRegimeRoute;
  JournalRoute: typeof JournalRoute;
  TradePlannerRoute: typeof TradePlannerRoute;
  SymbolsSymbolIdRoute: typeof SymbolsSymbolIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  NewsFeedRoute: NewsFeedRoute,
  ModeAnalysisRoute: ModeAnalysisRoute,
  MarketRegimeRoute: MarketRegimeRoute,
  JournalRoute: JournalRoute,
  TradePlannerRoute: TradePlannerRoute,
  SymbolsSymbolIdRoute: SymbolsSymbolIdRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
